// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCmsReportCustomProductMonth = "cms_report_custom_product_month"

// CmsReportCustomProductMonth 素材月报表
type CmsReportCustomProductMonth struct {
	ID                  int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AcceptMonth         string    `gorm:"column:accept_month;comment:日期" json:"accept_month"`              // 日期
	MediaType           int32     `gorm:"column:media_type;default:1;comment:1 快手 2 巨量" json:"media_type"` // 1 快手 2 巨量
	BusinessType        string    `gorm:"column:business_type;default:LA" json:"business_type"`
	AdvertiserID        string    `gorm:"column:advertiser_id;comment:媒体账户id" json:"advertiser_id"` // 媒体账户id
	UserID              int32     `gorm:"column:user_id" json:"user_id"`
	CustomerID          int32     `gorm:"column:customer_id;comment:客户id" json:"customer_id"` // 客户id
	ProductID           int32     `gorm:"column:product_id" json:"product_id"`
	ProductName         string    `gorm:"column:product_name" json:"product_name"`
	LastTermCost        float64   `gorm:"column:last_term_cost;comment:上周同比消耗" json:"last_term_cost"`      // 上周同比消耗
	Cost                float64   `gorm:"column:cost;comment:消耗" json:"cost"`                              // 消耗
	NewUnitNum          int32     `gorm:"column:new_unit_num;comment:新增计划数" json:"new_unit_num"`           // 新增计划数
	NewSucUnitNum       int32     `gorm:"column:new_suc_unit_num;comment:新增过审计划数" json:"new_suc_unit_num"` // 新增过审计划数
	AvgNewUnitNum       int32     `gorm:"column:avg_new_unit_num;comment:日均新增计划数" json:"avg_new_unit_num"` // 日均新增计划数
	CostUnitNum         int32     `gorm:"column:cost_unit_num;comment:有消耗计划数" json:"cost_unit_num"`        // 有消耗计划数
	InsertTime          time.Time `gorm:"column:insert_time;comment:插入时间" json:"insert_time"`              // 插入时间
	BusinessUsername    string    `gorm:"column:business_username;comment:商务" json:"business_username"`    // 商务
	CustomerType        int32     `gorm:"column:customer_type;comment:客户类型" json:"customer_type"`          // 客户类型
	OperatorType        int32     `gorm:"column:operator_type;comment:运营方式" json:"operator_type"`          // 运营方式
	GroupID             int32     `gorm:"column:group_id" json:"group_id"`
	AccountAgentType    string    `gorm:"column:account_agent_type" json:"account_agent_type"`
	OperatorAssistantID int32     `gorm:"column:operator_assistant_id;comment:运营助理" json:"operator_assistant_id"`    // 运营助理
	ManagedUnitNum      int32     `gorm:"column:managed_unit_num;comment:托管新增计划" json:"managed_unit_num"`            // 托管新增计划
	ManulUnitNum        int32     `gorm:"column:manul_unit_num;comment:手工新增计划" json:"manul_unit_num"`                // 手工新增计划
	AvgManagedUnitNum   int32     `gorm:"column:avg_managed_unit_num;comment:托管新增计划-日均" json:"avg_managed_unit_num"` // 托管新增计划-日均
	AvgManulUnitNum     int32     `gorm:"column:avg_manul_unit_num;comment:手工新增计划-日均" json:"avg_manul_unit_num"`     // 手工新增计划-日均
	ManagedSucUnitNum   int32     `gorm:"column:managed_suc_unit_num;comment:托管审核成功计划" json:"managed_suc_unit_num"`  // 托管审核成功计划
	ManulSucUnitNum     int32     `gorm:"column:manul_suc_unit_num;comment:手工审核成功计划" json:"manul_suc_unit_num"`      // 手工审核成功计划
}

// TableName CmsReportCustomProductMonth's table name
func (*CmsReportCustomProductMonth) TableName() string {
	return TableNameCmsReportCustomProductMonth
}
