// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCmsProduct = "cms_product"

// CmsProduct 产品信息表
type CmsProduct struct {
	ID                   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CustomerID           int32  `gorm:"column:customer_id;comment:客户id" json:"customer_id"`                           // 客户id
	UserID               int32  `gorm:"column:user_id;comment:绑定的运营用户id" json:"user_id"`                              // 绑定的运营用户id
	ProductName          string `gorm:"column:product_name;comment:产品名称" json:"product_name"`                         // 产品名称
	Remarks              string `gorm:"column:remarks;comment:备注" json:"remarks"`                                     // 备注
	State                int32  `gorm:"column:state;default:1;comment:状态 -1：停用 1：正常" json:"state"`                    // 状态 -1：停用 1：正常
	IndustryID           int32  `gorm:"column:industry_id;comment:行业id" json:"industry_id"`                           // 行业id
	IndustryChildID      int32  `gorm:"column:industry_child_id;comment:行业id" json:"industry_child_id"`               // 行业id
	IndustryThirdChildID int32  `gorm:"column:industry_third_child_id;comment:行业三级类目" json:"industry_third_child_id"` // 行业三级类目
	CreateUserID         int32  `gorm:"column:create_user_id;comment:创建人id" json:"create_user_id"`                    // 创建人id
	/*
		视频名称生成规则，link_symbol 连接符 "-" 或 "_", rule 1:利益点 2:视频关键词 3:日期 4:序号  如：{
			"link_symbol" : "_",
			"rule" => [1, 2, 3, 4]
		}
	*/
	VideoNameRule       string    `gorm:"column:video_name_rule;comment:视频名称生成规则，link_symbol 连接符 "-" 或 "_", rule 1:利益点 2:视频关键词 3:日期 4:序号  如：{\n	"link_symbol" : "_",\n	"rule" => [1, 2, 3, 4]\n}" json:"video_name_rule"`
	VideoBeginNum       int32     `gorm:"column:video_begin_num;default:1000;comment:视频名称自动生成 序号的起始数字（每次生成新的+1）" json:"video_begin_num"`         // 视频名称自动生成 序号的起始数字（每次生成新的+1）
	VideoNameRuleLyList string    `gorm:"column:video_name_rule_ly_list;comment:视频名称生成里面的利益点列表 如：["大流量", "转换好"]" json:"video_name_rule_ly_list"` // 视频名称生成里面的利益点列表 如：["大流量", "转换好"]
	CustomerIds         string    `gorm:"column:customer_ids;comment:手动关联的客户id，多个逗号隔开" json:"customer_ids"`                                      // 手动关联的客户id，多个逗号隔开
	DocURL              string    `gorm:"column:doc_url;comment:产品文档地址" json:"doc_url"`                                                          // 产品文档地址
	Logo                string    `gorm:"column:logo;comment:产品logo" json:"logo"`                                                                // 产品logo
	OperatorID          int32     `gorm:"column:operator_id;comment:运营" json:"operator_id"`                                                      // 运营
	AddTime             TimeNormal `gorm:"column:add_time;comment:添加时间" json:"add_time"`                                                          // 添加时间
	UpdateTime          TimeNormal `gorm:"column:update_time;comment:更新时间" json:"update_time"`                                                    // 更新时间
	FsDocToken          string    `gorm:"column:fs_doc_token;comment:飞书对接文档token" json:"fs_doc_token"`                                           // 飞书对接文档token
	FsDocUserID         int32     `gorm:"column:fs_doc_user_id;comment:飞书文档创建人" json:"fs_doc_user_id"`                                           // 飞书文档创建人
	FsDocCreateTime     TimeNormal `gorm:"column:fs_doc_create_time;comment:飞书文档创建时间" json:"fs_doc_create_time"`                                  // 飞书文档创建时间
	FsDocUpdateTime     TimeNormal `gorm:"column:fs_doc_update_time;comment:飞书文档更新时间" json:"fs_doc_update_time"`                                  // 飞书文档更新时间
	IsPoint             int32     `gorm:"column:is_point;default:1;comment:是否是重点产品 1:不是 2：是" json:"is_point"`                                    // 是否是重点产品 1:不是 2：是
	MaterialDirection   string    `gorm:"column:material_direction;comment:素材方向" json:"material_direction"`                                      // 素材方向
	PutType             int32     `gorm:"column:put_type;comment:产品类型 1:代播代投 2:仅代投" json:"put_type"`                                             // 产品类型 1:代播代投 2:仅代投
}

// TableName CmsProduct's table name
func (*CmsProduct) TableName() string {
	return TableNameCmsProduct
}
