// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCmsMediaAccount = "cms_media_account"

// CmsMediaAccount 媒体账号管理
type CmsMediaAccount struct {
	ID                     int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CustomerID             int32     `gorm:"column:customer_id;comment:客户id" json:"customer_id"`                                         // 客户id
	CrmID                  string    `gorm:"column:crm_id;comment:crm端的id" json:"crm_id"`                                                // crm端的id
	ProductID              int32     `gorm:"column:product_id;comment:产品id" json:"product_id"`                                           // 产品id
	UserID                 int32     `gorm:"column:user_id;comment:分配的用户id(运营)" json:"user_id"`                                          // 分配的用户id(运营)
	BusinessUserID         int32     `gorm:"column:business_user_id;comment:商务负责人用户id" json:"business_user_id"`                          // 商务负责人用户id
	MediaID                int32     `gorm:"column:media_id;comment:媒体id" json:"media_id"`                                               // 媒体id
	MediaName              string    `gorm:"column:media_name;comment:媒体名称" json:"media_name"`                                           // 媒体名称
	Type                   int32     `gorm:"column:type;default:1;comment:运营方式 1：自运营(自) 2：二代运营(收) 4：客户运营(走)" json:"type"`                // 运营方式 1：自运营(自) 2：二代运营(收) 4：客户运营(走)
	CustomerType           int32     `gorm:"column:customer_type;default:1;comment:客户类型 1：直客 2：渠道 3：代运营" json:"customer_type"`           // 客户类型 1：直客 2：渠道 3：代运营
	State                  int32     `gorm:"column:state;default:1;comment:状态 -1：停用 1：正常 2：暂停投放" json:"state"`                           // 状态 -1：停用 1：正常 2：暂停投放
	AuthState              int32     `gorm:"column:auth_state;default:-1;comment:授权状态 -1：未授权 1：以授权" json:"auth_state"`                   // 授权状态 -1：未授权 1：以授权
	AccountName            string    `gorm:"column:account_name;comment:账户昵称" json:"account_name"`                                       // 账户昵称
	AccountID              string    `gorm:"column:account_id;comment:账号ID（媒体端）" json:"account_id"`                                      // 账号ID（媒体端）
	AdvertiserID           string    `gorm:"column:advertiser_id;comment:广告主ID(媒体端)" json:"advertiser_id"`                               // 广告主ID(媒体端)
	DeveloperAccountID     int32     `gorm:"column:developer_account_id;default:1;comment:对应的媒体开发者账号配置表的id" json:"developer_account_id"` // 对应的媒体开发者账号配置表的id
	BusinessType           string    `gorm:"column:business_type;default:LA;comment:业务类型 1：LA 2:KA" json:"business_type"`                // 业务类型 1：LA 2:KA
	AuthTime               TimeNormal `gorm:"column:auth_time;comment:授权时间" json:"auth_time"`                                             // 授权时间
	FirstIndustry          string    `gorm:"column:first_industry;comment:一级行业" json:"first_industry"`                                   // 一级行业
	SecondIndustry         string    `gorm:"column:second_industry;comment:二级行业" json:"second_industry"`                                 // 二级行业
	AgentUserID            int32     `gorm:"column:agent_user_id;comment:代理用户id" json:"agent_user_id"`                                   // 代理用户id
	AddTime                TimeNormal `gorm:"column:add_time;comment:添加时间" json:"add_time"`                                               // 添加时间
	UpdateTime             TimeNormal `gorm:"column:update_time;comment:更新时间" json:"update_time"`                                         // 更新时间
	RefundRatio            float64   `gorm:"column:refund_ratio;default:0.00" json:"refund_ratio"`
	AccountAgentType       int32     `gorm:"column:account_agent_type;comment:账户代理商类型  1:巨量引擎, 2:巨量千川, 3:磁力引擎, 4:磁力金牛, 5:广点通, 7:超级汇川(UC)" json:"account_agent_type"` // 账户代理商类型  1:巨量引擎, 2:巨量千川, 3:磁力引擎, 4:磁力金牛, 5:广点通, 7:超级汇川(UC)
	AssistantUserIds       string    `gorm:"column:assistant_user_ids;comment:协作人id列表" json:"assistant_user_ids"`                                                    // 协作人id列表
	MaterialCategory       string    `gorm:"column:material_category" json:"material_category"`
	SchedulingSwitch       int32     `gorm:"column:scheduling_switch;default:1;comment:轮班开关 1：关闭 2：打开" json:"scheduling_switch"`                    // 轮班开关 1：关闭 2：打开
	OperatorAssistant      int32     `gorm:"column:operator_assistant;comment:运营助理" json:"operator_assistant"`                                      // 运营助理
	CompanySubject         string    `gorm:"column:company_subject;comment:公司主体" json:"company_subject"`                                            // 公司主体
	IntoDbTime             TimeNormal `gorm:"column:into_db_time;comment:入库时间" json:"into_db_time"`                                                  // 入库时间
	IsDistributionServicer bool      `gorm:"column:is_distribution_servicer;default:1;comment:是否分配服务商 1：未分配 2：已分配" json:"is_distribution_servicer"` // 是否分配服务商 1：未分配 2：已分配
	ServicerID             int32     `gorm:"column:servicer_id;comment:服务商ID" json:"servicer_id"`                                                   // 服务商ID
	AutoHideComments       int32     `gorm:"column:auto_hide_comments;default:2;comment:自动屏蔽评论 1：是 2：否" json:"auto_hide_comments"`                  // 自动屏蔽评论 1：是 2：否
	IsValid                int32     `gorm:"column:is_valid;default:1;comment:是否有效 1:有效(默认) 2:无效  根据账户创建时间和消耗确定" json:"is_valid"`                   // 是否有效 1:有效(默认) 2:无效  根据账户创建时间和消耗确定
}

// TableName CmsMediaAccount's table name
func (*CmsMediaAccount) TableName() string {
	return TableNameCmsMediaAccount
}
