// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model


const TableNameCrmScreenshotJob = "crm_screenshot_job"

// CrmScreenshotJob mapped from table <crm_screenshot_job>
type CrmScreenshotJob struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"` // 主键id
	JobNo         string    `gorm:"column:job_no" json:"job_no"`
	MediaType     int32     `gorm:"column:media_type" json:"media_type"`
	BusinessType  string     `gorm:"column:business_type" json:"business_type"`
	Type          string    `gorm:"column:type" json:"type"`
	BeginTime     TimeNormal `gorm:"column:begin_time" json:"begin_time"`
	EndTime       TimeNormal `gorm:"column:end_time" json:"end_time"`
	AdvertiserIds string    `gorm:"column:advertiser_ids" json:"advertiser_ids"`
	URL           string    `gorm:"column:url" json:"url"`
	Status        int      `gorm:"column:status;comment:0未开始1进行中2截图成功3截图失败" json:"status"` // 0未开始1进行中2截图成功4截图失败
	FailMsg       string    `gorm:"column:fail_msg;comment:失败原因" json:"fail_msg"`           // 失败原因
	AddTime       TimeNormal `gorm:"column:add_time;comment:创建时间" json:"add_time"`           // 创建时间
	UpdateTime    TimeNormal `gorm:"column:update_time;comment:更新时间" json:"update_time"`     // 更新时间
}

// TableName CrmScreenshotJob's table name
func (*CrmScreenshotJob) TableName() string {
	return TableNameCrmScreenshotJob
}
