// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCrmUser = "crm_user"

// CrmUser 系统用户表
type CrmUser struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username     string    `gorm:"column:username;comment:账号" json:"username"`                  // 账号
	Password     string    `gorm:"column:password;comment:密码" json:"password"`                  // 密码
	Email        string    `gorm:"column:email;comment:邮箱" json:"email"`                        // 邮箱
	Realname     string    `gorm:"column:realname;comment:姓名" json:"realname"`                  // 姓名
	Phone        string    `gorm:"column:phone;comment:手机号" json:"phone"`                       // 手机号
	FeishuUserID string    `gorm:"column:feishu_user_id;comment:飞书的用户id" json:"feishu_user_id"` // 飞书的用户id
	RoleID       int32     `gorm:"column:role_id;comment:角色id" json:"role_id"`                  // 角色id
	DepartmentID int32     `gorm:"column:department_id;comment:部门id" json:"department_id"`      // 部门id
	State        int32     `gorm:"column:state;default:1;comment:状态 -1：停用 1：正常" json:"state"`   // 状态 -1：停用 1：正常
	AddTime      TimeNormal `gorm:"column:add_time;comment:添加时间" json:"add_time"`                // 添加时间
	UpdateTime   TimeNormal `gorm:"column:update_time;comment:更新时间" json:"update_time"`          // 更新时间
	EntryTime    TimeNormal `gorm:"column:entry_time;comment:入职时间" json:"entry_time"`            // 入职时间
	LeaveTime    TimeNormal `gorm:"column:leave_time;comment:离职时间" json:"leave_time"`            // 离职时间
	RoleIds      string    `gorm:"column:role_ids;comment:新版角色字段" json:"role_ids"`              // 新版角色字段
}

// TableName CrmUser's table name
func (*CrmUser) TableName() string {
	return TableNameCrmUser
}
